# Generated by Django 4.2.6 on 2023-11-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='data',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(null=True, upload_to='csv_files/'),
        ),
    ]
